import nextVitals from "eslint-config-next/core-web-vitals";

const eslintConfig = [
  ...nextVitals,
  {
    ignores: [
      ".next/**",
      // Generated by the Cloudflare adapter; not source.
      ".open-next/**",
      ".wrangler/**",
      "node_modules/**",
    ],
  },
];

export default eslintConfig;
